In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'c:\\Users\\tungf\\Desktop\\Vs code 資料\\rehab-accessibility-tainan\\notebooks'

In [3]:
file_path = "../data/raw/population_age_tainan_2025_12.csv"

In [4]:
file_path

'../data/raw/population_age_tainan_2025_12.csv'

In [5]:
df = pd.read_csv(file_path)

In [6]:
df.head()

,Seq,區域別,性別,總計,合計0至4歲,0歲,1歲,2歲,3歲,4歲,...,92歲,93歲,94歲,合計95至99歲,95歲,96歲,97歲,98歲,99歲,100歲以上
0,1,臺南市,計,1852477,49815,7040,9997,10146,10587,12045,...,2069,1625,1398,2847,1065,711,512,351,208,339
1,2,臺南市,男,917451,26055,3735,5201,5257,5557,6305,...,700,581,478,1009,395,253,178,114,69,113
2,3,臺南市,女,935026,23760,3305,4796,4889,5030,5740,...,1369,1044,920,1838,670,458,334,237,139,226
3,4,新營區,計,74493,1832,265,397,337,386,447,...,100,69,66,123,49,28,25,13,8,15
4,5,新營區,男,36397,944,137,202,169,206,230,...,27,23,22,38,15,10,7,3,3,5

In [7]:
df.shape

(114, 125)

In [8]:
df["性別"].value_counts()

性別
計    38
男    38
女    38
Name: count, dtype: int64

In [9]:
df_total = df[df["性別"] == "計"].copy()

In [10]:
df_total.shape

(38, 125)

In [11]:
df_district = df_total[df_total["區域別"] != "臺南市"].copy()

In [12]:
df_district.shape

(37, 125)

In [13]:
columns_to_keep = [
    "區域別",
    "總計",
    "合計65至69歲",
    "合計70至74歲",
    "合計75至79歲",
    "合計80至84歲",
    "合計85至89歲",
    "合計90至94歲",
    "合計95至99歲",
    "100歲以上"
]

In [14]:
columns_to_keep

['區域別',
 '總計',
 '合計65至69歲',
 '合計70至74歲',
 '合計75至79歲',
 '合計80至84歲',
 '合計85至89歲',
 '合計90至94歲',
 '合計95至99歲',
 '100歲以上']

In [15]:
df_population = df_district[columns_to_keep].copy()

In [16]:
df_population.shape

(37, 10)

In [17]:
df_population.head()

,區域別,總計,合計65至69歲,合計70至74歲,合計75至79歲,合計80至84歲,合計85至89歲,合計90至94歲,合計95至99歲,100歲以上
3,新營區,74493,5411,4536,2782,1707,1164,514,123,15
6,鹽水區,23635,1892,1475,950,675,526,270,52,1
9,白河區,24948,2157,1860,1275,887,750,397,96,11
12,柳營區,19831,1631,1346,850,604,414,204,40,3
15,後壁區,20840,1819,1514,1081,833,623,348,77,9

In [18]:
df_population.dtypes

區域別           str
總計          int64
合計65至69歲    int64
合計70至74歲    int64
合計75至79歲    int64
合計80至84歲    int64
合計85至89歲    int64
合計90至94歲    int64
合計95至99歲    int64
100歲以上      int64
dtype: object

In [19]:
age_65_plus_cols = [
    "合計65至69歲",
    "合計70至74歲",
    "合計75至79歲",
    "合計80至84歲",
    "合計85至89歲",
    "合計90至94歲",
    "合計95至99歲",
    "100歲以上"
]

In [20]:
age_65_plus_cols

['合計65至69歲',
 '合計70至74歲',
 '合計75至79歲',
 '合計80至84歲',
 '合計85至89歲',
 '合計90至94歲',
 '合計95至99歲',
 '100歲以上']

In [21]:
df_population["population_65_plus"] = df_population[age_65_plus_cols].sum(axis=1)

In [22]:
df_population[["區域別", "總計", "population_65_plus"]].head()

    區域別     總計  population_65_plus
3   新營區  74493               16252
6   鹽水區  23635                5841
9   白河區  24948                7433
12  柳營區  19831                5092
15  後壁區  20840                6304

In [23]:
(df_population["population_65_plus"] <= df_population["總計"]).all()

np.True_

In [24]:
df_population["pct_65_plus"] = (
    df_population["population_65_plus"]
    / df_population["總計"]
    * 100
)

In [25]:
df_population[
    ["區域別", "總計", "population_65_plus", "pct_65_plus"]
].head()

    區域別     總計  population_65_plus  pct_65_plus
3   新營區  74493               16252    21.816815
6   鹽水區  23635                5841    24.713349
9   白河區  24948                7433    29.793971
12  柳營區  19831                5092    25.676970
15  後壁區  20840                6304    30.249520

In [26]:
df_population[
    ["區域別", "總計", "population_65_plus", "pct_65_plus"]
]

     區域別      總計  population_65_plus  pct_65_plus
3    新營區   74493               16252    21.816815
6    鹽水區   23635                5841    24.713349
9    白河區   24948                7433    29.793971
12   柳營區   19831                5092    25.676970
15   後壁區   20840                6304    30.249520
18   東山區   18490                5351    28.939968
21   麻豆區   42873               10101    23.560283
24   下營區   21742                5872    27.007635
27   六甲區   20880                4975    23.826628
30   官田區   20527                4557    22.200029
33   大內區    8427                2622    31.114276
36   佳里區   58328               12396    21.252229
39   學甲區   24365                5763    23.652781
42   西港區   24811                5236    21.103543
45   七股區   20493                5002    24.408335
48   將軍區   17598                4784    27.184907
51   北門區    9436                2405    25.487495
54   新化區   41932                9260    22.083373
57   善化區   53888                9161    17.000074
60   新市區   38279                6486    16.944016
63   安定區   29783                5876    19.729376
66   山上區    6796                1711    25.176574
69   玉井區   12674                3670    28.956920
72   楠西區    8392                2545    30.326501
75   南化區    7606                2255    29.647647
78   左鎮區    4095                1380    33.699634
81   仁德區   77496               15094    19.477134
84   歸仁區   70574               12993    18.410463
87   關廟區   33198                7977    24.028556
90   龍崎區    3234                1158    35.807050
93   永康區  235805               38622    16.378788
96    東區  180856               35950    19.877693
99    南區  119121               27590    23.161323
102   北區  125439               26136    20.835625
105  安南區  204534               32872    16.071656
108  安平區   71256               11327    15.896205
111  中西區   75802               17327    22.858236

In [27]:
output_path = "../data/processed/population_tainan_2025_clean.csv"

In [28]:
df_population.to_csv(output_path, index=False, encoding="utf-8-sig")