In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/clinic_specialty_2024/clinic_sp113.csv"

In [3]:
df_clinic = pd.read_csv(file_path)

In [4]:
df_clinic.shape

(366, 47)

In [5]:
df_clinic.head()

,鄉鎮市區碼,診所家數,家庭醫學科,內科,外科,兒科,婦產科,骨科,神經科,神經外科,...,植牙科,中醫一般科,中醫內科,中醫外科,中醫眼科,中醫兒科,中醫婦科,中醫傷科,中醫針灸科,中醫痔科
0,101,325,11,17,9,14,4,4,1,0,...,0,43,0,0,0,0,0,0,0,0
1,102,965,29,26,23,22,34,9,4,0,...,0,130,1,0,0,0,0,0,0,0
2,109,169,9,12,1,7,4,1,2,0,...,0,41,1,0,0,0,0,0,0,0
3,110,534,23,23,9,16,25,7,4,0,...,0,87,0,0,0,0,0,0,0,0
4,111,289,10,22,6,13,9,5,2,0,...,0,38,0,0,0,0,0,0,0,0

In [6]:
df_clinic.columns

Index(['鄉鎮市區碼', '診所家數', '家庭醫學科', '內科', '外科', '兒科', '婦產科', '骨科', '神經科', '神經外科',
       '泌尿科', '耳鼻喉科', '眼科', '皮膚科', '精神科', '復健科', '麻醉科', '放射診斷科', '放射腫瘤科',
       '解剖病理科', '臨床病理科', '核子醫學科', '急診醫學科', '整形外科', '職業醫學科', '西醫一般科', '牙醫一般科',
       '口腔病理科', '口腔顎面外科', '齒顎矯正科', '牙周病科', '兒童牙科', '牙髓病科', '?復補綴牙科', '牙體復形科',
       '家庭牙醫科', '特殊需求者口腔醫學科', '植牙科', '中醫一般科', '中醫內科', '中醫外科', '中醫眼科', '中醫兒科',
       '中醫婦科', '中醫傷科', '中醫針灸科', '中醫痔科'],
      dtype='str')

In [7]:
df_clinic["鄉鎮市區碼"].head(10)

0    101
1    102
2    109
3    110
4    111
5    112
6    115
7    116
8    117
9    118
Name: 鄉鎮市區碼, dtype: int64

In [9]:
tainan_check = df_clinic[
    df_clinic["鄉鎮市區碼"].between(501, 538)
    ]

In [10]:
tainan_check.shape

(37, 47)

In [11]:
tainan_check["鄉鎮市區碼"].tolist()

[501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 537,
 538]

In [12]:
df_clinic["鄉鎮市區碼"].between(501, 538)

0      False
1      False
2      False
3      False
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: 鄉鎮市區碼, Length: 366, dtype: bool

In [13]:
lookup_path = "../data/raw/clinic_specialty_2024/欄位說明.csv"

In [14]:
df_lookup = pd.read_csv(lookup_path)

In [15]:
df_lookup.head()

   鄉鎮市區碼 鄉鎮市區名稱(101、102年適用) 鄉鎮市區名稱(103年以後適用)
0    101             臺北市松山區           臺北市松山區
1    102             臺北市大安區           臺北市大安區
2    109             臺北市大同區           臺北市大同區
3    110             臺北市中山區           臺北市中山區
4    111             臺北市內湖區           臺北市內湖區

In [16]:
df_lookup.columns

Index(['鄉鎮市區碼', '鄉鎮市區名稱(101、102年適用)', '鄉鎮市區名稱(103年以後適用)'], dtype='str')

In [17]:
lookup_2024 = df_lookup[
    ["鄉鎮市區碼", "鄉鎮市區名稱(103年以後適用)"]
].copy()

In [18]:
lookup_2024.columns = ["鄉鎮市區碼", "district_full"]

In [19]:
lookup_tainan = lookup_2024[
    lookup_2024["鄉鎮市區碼"].between(501, 538)
].copy()

In [20]:
lookup_tainan.shape

(37, 2)

In [21]:
lookup_tainan.head()

    鄉鎮市區碼 district_full
41    501        臺南市新營區
42    502        臺南市鹽水區
43    503        臺南市白河區
44    504        臺南市麻豆區
45    505        臺南市佳里區

In [22]:
df_clinic_tainan = tainan_check.merge(
    lookup_tainan,
    on="鄉鎮市區碼",
    how="left"
)

In [23]:
df_clinic_tainan.shape

(37, 48)

In [24]:
df_clinic_tainan[
    ["鄉鎮市區碼", "district_full", "復健科"]
].head()

   鄉鎮市區碼 district_full  復健科
0    501        臺南市新營區    2
1    502        臺南市鹽水區    0
2    503        臺南市白河區    1
3    504        臺南市麻豆區    1
4    505        臺南市佳里區    2

In [25]:
df_clinic_tainan["district_full"].isna().sum()

np.int64(0)

In [26]:
df_clinic_tainan["鄉鎮市區碼"].duplicated().sum()

np.int64(0)

In [27]:
df_clinic_tainan["復健科"].isna().sum()

np.int64(0)

In [28]:
df_rehab_clinic = df_clinic_tainan[
    ["district_full", "復健科"]
].copy()

In [29]:
df_rehab_clinic.columns = [
    "district",
    "rehab_clinic_count"
]

In [30]:
df_rehab_clinic["district"] = (
    df_rehab_clinic["district"]
    .str.removeprefix("臺南市")
)

In [31]:
df_rehab_clinic.head()

  district  rehab_clinic_count
0      新營區                   2
1      鹽水區                   0
2      白河區                   1
3      麻豆區                   1
4      佳里區                   2

In [32]:
df_rehab_clinic.shape

(37, 2)

In [33]:
df_rehab_clinic.dtypes

district                str
rehab_clinic_count    int64
dtype: object

In [34]:
df_rehab_clinic["district"].duplicated().sum()

np.int64(0)

In [35]:
df_rehab_clinic.isna().sum()

district              0
rehab_clinic_count    0
dtype: int64

In [36]:
output_path = "../data/processed/rehab_clinics_tainan_2024_clean.csv"

In [37]:
df_rehab_clinic.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)